<a href="https://colab.research.google.com/github/bihjane/Data-science-and-AI-K-12-teaching-tools/blob/main/Copy_of_Titanic_Preprocessing_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Titanic Data Preprocessing — Student Exercise
## Complete the Preprocessing Pipeline

This notebook is your version of the Titanic preprocessing pipeline. Wherever
you see a **`# TODO`** comment, write the code that accomplishes it — use the
**Data Preprocessing Cheat Sheet** for the exact syntax and to see which row
each step corresponds to.

A few tips:
- Run each cell as you finish it. The `print()` statements already in the
  cells are there so you can sanity-check your output before moving on.
- Some cells build on variables created in earlier cells (`df`, `X`,
  `preprocessor`, etc.) — run the notebook top to bottom, in order.
- If a cell errors out with a `NameError`, it usually means a TODO above it
  still needs to be filled in.

## Section 1: Load and Explore the Data

In [120]:
# TODO 1: Import pandas as pd and numpy as np
# TODO 2: Import ColumnTransformer from sklearn.compose
# TODO 3: Import OrdinalEncoder, StandardScaler, and OneHotEncoder from sklearn.preprocessing
#         (Cheat sheet: "Import core libraries", "Import encoding / scaling tools",
#          "Import the pipeline transformer")


import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

########################### Dataset from Google Drive ##################
import os
import gdown

url = 'https://drive.google.com/file/d/1QRzUKdImSsQutx82CX8kidiJ2YT4_lYP/view?usp=sharing'
output_path = 'Titanic_Train.csv'

if not os.path.exists(output_path):
    print("Downloading dataset...")
    # TODO 4: Use gdown.download() to download the file at `url` to `output_path`.
    #         Pass quiet=False and fuzzy=True so it works with a share link.
    #         (Cheat sheet: "Read in a CSV hosted on Google Drive")
    gdown.download(url, output_path, quiet=False, fuzzy=True)
    print("Download complete!")
else:
    print("Dataset already exists.")
########################################################################

# TODO 5: Load output_path into a DataFrame called df
# TODO 6: Print an f-string with the shape of df, e.g. "Dataset loaded successfully! Shape: ..."

Dataset already exists.

In [121]:
# TODO: Display the first 5 rows of df

df = pd.read_csv('Titanic_Train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [122]:
# TODO 1: Import pandas as pd and numpy as np
# TODO 2: Import ColumnTransformer from sklearn.compose
# TODO 3: Import OrdinalEncoder, StandardScaler, and OneHotEncoder from sklearn.preprocessing
#         (Cheat sheet: "Import core libraries", "Import encoding / scaling tools",
#          "Import the pipeline transformer")




########################### Dataset from Google Drive ##################
import os
import gdown

url = 'https://drive.google.com/file/d/1QRzUKdImSsQutx82CX8kidiJ2YT4_lYP/view?usp=sharing'
output_path = 'Titanic_Train.csv'

if not os.path.exists(output_path):
    print("Downloading dataset...")
    # TODO 4: Use gdown.download() to download the file at `url` to `output_path`.
    #         Pass quiet=False and fuzzy=True so it works with a share link.
    #         (Cheat sheet: "Read in a CSV hosted on Google Drive")

    print("Download complete!")
else:
    print("Dataset already exists.")
########################################################################

# TODO 5: Load output_path into a DataFrame called df
# TODO 6: Print an f-string with the shape of df, e.g. "Dataset loaded successfully! Shape: ..."

Dataset already exists.

In [123]:
# TODO: Get information about the dataset (column names, data types, non-null counts)

In [124]:
# TODO: Get descriptive statistics for the numeric columns
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [125]:
# TODO: Check for missing values
# 1) Print the count of missing values per column
# 2) Print the PERCENTAGE of missing values per column
# (Cheat sheet: "Check missing values (count)" and "Check missing values (percent)")
print(df.isnull().sum())
print((df.isnull().sum() / len(df)) * 100)
print(df.dtypes)
print(df['Embarked'].value_counts())
print(df.columns.tolist())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

## Section 2: Handle Missing Values

In [126]:
# TODO: Drop the 'Cabin' column — about 77% of its values are missing,
#       which is too many to impute reliably.
# Print the number of columns before and after dropping it, so you can confirm it worked.
print(f"Columns before: {df.shape[1]}")
df = df.drop('Cabin', axis=1)
print(f"Columns after: {df.shape[1]}")

Columns before: 12
Columns after: 11

In [127]:
# TODO: Fill missing 'Age' values with the median (median is robust to outliers)
# 1) Compute the median age and store it in a variable called median_age
# 2) Print median_age
# 3) Print how many Age values are missing BEFORE filling
# 4) Fill the missing Age values with median_age
# 5) Print how many Age values are missing AFTER filling (should be 0)
median_age = df['Age'].median()
print(median_age)
print(df['Age'].isnull().sum())
df['Age'].fillna(median_age, inplace=True)
print(df['Age'].isnull().sum())

28.0
177
0

/tmp/ipykernel_2186/3721338113.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(median_age, inplace=True)

In [128]:
# TODO: Fill missing 'Embarked' values with the mode (most frequent value)
# 1) Compute the mode of Embarked and store it in a variable called mode_embarked
#    (remember .mode() returns a Series — you want its first value)
# 2) Print mode_embarked
# 3) Print how many Embarked values are missing BEFORE filling
# 4) Fill the missing Embarked values with mode_embarked
# 5) Print how many Embarked values are missing AFTER filling (should be 0)
mode_embarked = df['Embarked'].mode()[0]
print(mode_embarked)
print(df['Embarked'].isnull().sum())
df['Embarked'].fillna(mode_embarked, inplace=True)
print(df['Embarked'].isnull().sum())

S
2
0

/tmp/ipykernel_2186/3700639470.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(mode_embarked, inplace=True)

In [129]:
# TODO: Verify no missing values remain anywhere in df
# Print a success message if the total missing count is 0,
# otherwise print which columns still have missing values.
print(df.isnull().sum().sum())
assert df.isnull().sum().sum() == 0

0

## Section 3: Select Features for Machine Learning

In [130]:
# TODO: Drop columns that won't be useful for prediction: 'PassengerId', 'Name', 'Ticket'
# In a comment, briefly say why each one isn't useful as-is:
#   PassengerId: ...
#   Name: ...
#   Ticket: ...
# Print the number of columns before and after, and the list of remaining columns.
print(f"Columns before: {df.shape[1]}")
df = df.drop(['PassengerId', 'Name', 'Ticket'], axis=1)
print(f"Columns after: {df.shape[1]}")
print(df.columns.tolist())

Columns before: 11
Columns after: 8
['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

In [131]:
# TODO: Separate features and target
# X = every column except 'Survived'
# y = the 'Survived' column
# Print the shapes of X and y, and the list of X's columns.
X = df.drop('Survived', axis=1)
y = df['Survived']
print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")
print(X.columns.tolist())

X shape: (891, 7)
y shape: (891,)
['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

In [132]:
# TODO: Display info about the feature matrix X (X.info())
print((X.info()))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    891 non-null    int64
 1   Sex       891 non-null    object
 2   Age       891 non-null    float64
 3   SibSp     891 non-null    int64
 4   Parch     891 non-null    int64
 5   Fare      891 non-null    float64
 6   Embarked  891 non-null    object
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB
None

## Section 4: One-Hot Encode Categorical Variables Using Scikit-Learn

In [133]:
# TODO: Sort the remaining feature columns into three groups:
#   categorical_columns  -> multi-category columns to ONE-HOT encode      (Pclass, Embarked)
#   binary_columns        -> two-category column to ORDINAL encode        (Sex)
#   numerical_columns      -> columns to SCALE                            (Age, SibSp, Parch, Fare)
#
# categorical_columns = [...]
# binary_columns = [...]
# numerical_columns = [...]

# TODO: Print each of the three lists

# TODO: Print the unique values found in the categorical columns and in the binary columns
#       (loop over each column list and print col: X[col].unique())

numerical_columns = ['Age', 'SibSp', 'Parch', 'Fare']
categorical_columns = ['Pclass', 'Embarked','Sex']

In [134]:
# TODO: Create one transformer per column group (Cheat sheet, Option B — ColumnTransformer Pipeline)
# categorical_transformer = ...   # OneHotEncoder — set sparse_output=False
# numerical_transformer   = ...   # StandardScaler
# binary_transformer      = ...   # OrdinalEncoder
numerical_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(sparse_output=False)

In [145]:
# TODO: Build the ColumnTransformer
# Combine the three transformers above, each paired with its matching column list.
# Name the three pieces 'num', 'cat', and 'bin' (Cheat sheet, Option B).
#
# preprocessor = ColumnTransformer(transformers=[
#     (...),
#     (...),
#     (...),
# ])

preprocessor = ColumnTransformer(transformers=[
    ('num', numerical_transformer, numerical_columns),
    ('cat', categorical_transformer, categorical_columns)
])

# TODO: Fit and transform X through preprocessor, storing the result in encoded_array
encoded_array = preprocessor.fit_transform(X)


# Column counts (uses your preprocessor and categorical_columns from above — no edits needed below)




num_cat_cols = len(preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_columns))
print(f"Encoded array shape: {encoded_array.shape}")
print(f"Original categorical columns: {len(categorical_columns)}")
print(f"New categorical encoded columns: {num_cat_cols}")
print(f"Numerical columns (unchanged): {len(numerical_columns)}")

Encoded array shape: (891, 12)
Original categorical columns: 3
New categorical encoded columns: 8
Numerical columns (unchanged): 4

In [146]:
# TODO: Get the generated feature names from preprocessor.get_feature_names_out()
# Store them in a variable called encoded_columns and print them
encoded_columns = preprocessor.get_feature_names_out()
print(encoded_columns)

# Then, in a comment, briefly explain in your own words what each prefix means:
#   num__   -> ...
#   cat__   -> ...
#   bin__   -> ...

['num__Age' 'num__SibSp' 'num__Parch' 'num__Fare' 'cat__Pclass_1'
 'cat__Pclass_2' 'cat__Pclass_3' 'cat__Embarked_C' 'cat__Embarked_Q'
 'cat__Embarked_S' 'cat__Sex_female' 'cat__Sex_male']

In [147]:
# TODO: Convert encoded_array into a DataFrame called X_encoded
#   - use encoded_columns as the column names
#   - use X.index as the index
X_encoded = pd.DataFrame(encoded_array, columns=encoded_columns, index=X.index)
# Display the first few rows.
print(f'Encoded shape: {X_encoded.shape}')

Encoded shape: (891, 12)

## Section 5: Final Verification

In [149]:
# TODO: Print the final shape of X_encoded (rows and columns).
# Compare it to the 7 features you had right before encoding — how many new columns did encoding add, and why?
print(f'Encoded shape: {X_encoded.shape}')

Encoded shape: (891, 12)

In [151]:
# TODO: Check whether any missing values remain in X_encoded
assert X.isnull().sum().sum() == 0

In [152]:
# TODO: Verify every column in X_encoded is numeric (check X_encoded.dtypes)
print(X_encoded.dtypes)

num__Age           float64
num__SibSp         float64
num__Parch         float64
num__Fare          float64
cat__Pclass_1      float64
cat__Pclass_2      float64
cat__Pclass_3      float64
cat__Embarked_C    float64
cat__Embarked_Q    float64
cat__Embarked_S    float64
cat__Sex_female    float64
cat__Sex_male      float64
dtype: object

In [153]:
# TODO: Print summary statistics for X_encoded
print(X_encoded.describe())

           num__Age    num__SibSp    num__Parch     num__Fare  cat__Pclass_1  \
count  8.910000e+02  8.910000e+02  8.910000e+02  8.910000e+02     891.000000
mean   2.272780e-16  4.386066e-17  5.382900e-17  3.987333e-18       0.242424
std    1.000562e+00  1.000562e+00  1.000562e+00  1.000562e+00       0.428790
min   -2.224156e+00 -4.745452e-01 -4.736736e-01 -6.484217e-01       0.000000
25%   -5.657365e-01 -4.745452e-01 -4.736736e-01 -4.891482e-01       0.000000
50%   -1.046374e-01 -4.745452e-01 -4.736736e-01 -3.573909e-01       0.000000
75%    4.333115e-01  4.327934e-01 -4.736736e-01 -2.424635e-02       0.000000
max    3.891554e+00  6.784163e+00  6.974147e+00  9.667167e+00       1.000000

       cat__Pclass_2  cat__Pclass_3  cat__Embarked_C  cat__Embarked_Q  \
count     891.000000     891.000000       891.000000       891.000000
mean        0.206510       0.551066         0.188552         0.086420
std         0.405028       0.497665         0.391372         0.281141
min         0.000000       0.000000         0.000000         0.000000
25%         0.000000       0.000000         0.000000         0.000000
50%         0.000000       1.000000         0.000000         0.000000
75%         0.000000       1.000000         0.000000         0.000000
max         1.000000       1.000000         1.000000         1.000000

       cat__Embarked_S  cat__Sex_female  cat__Sex_male
count       891.000000       891.000000     891.000000
mean          0.725028         0.352413       0.647587
std           0.446751         0.477990       0.477990
min           0.000000         0.000000       0.000000
25%           0.000000         0.000000       0.000000
50%           1.000000         0.000000       1.000000
75%           1.000000         1.000000       1.000000
max           1.000000         1.000000       1.000000

In [140]:
# TODO: Write a short final summary using print() statements, confirming:
#   - the original dataset shape and the final X_encoded shape
#   - which column was dropped, and why
#   - which columns were imputed, and how (median / mode)
#   - which columns were encoded, and how (one-hot / ordinal / scaled)
#   - that there are no missing values and all features are numeric

## Bonus: Save Preprocessed Data (Optional)

In [141]:
# TODO (optional): Combine X_encoded with y into one DataFrame (add a 'Survived' column)
# and save it to 'Titanic_Preprocessed.csv' using .to_csv(). Print the shape to confirm.

## Reflection Questions

Answer each of these in your own words — a few sentences each is plenty.

1. **Why median instead of mean for Age?**

   *Your answer:*

2. **Why drop Cabin instead of imputing it?**

   *Your answer:*

3. **What is the dummy variable trap, and how does dropping a category (or using `drop='first'`) avoid it?**

   *Your answer:*

4. **How many features ended up in the final dataset, and why is that different from the number of columns you started with?**

   *Your answer:*

5. **Is this dataset ready for a model like logistic regression? What would you check to be sure?**

   *Your answer:*